baseURL = "https://partrove.com/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
hasCJKLanguage = true
title = "互联网收藏夹"
theme = "dream"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"


# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "ParTrove"
description = "互联网收藏夹|分享互联网优质软件、干货资源和实用技巧。"
avatar = "https://gn-img-a1.partrove.com/common/site/avatar.png"
headerTitle = "互联网收藏夹"
motto = "分享互联网优质软件、干货资源和实用技巧。"
images = ['https://gn-img-a1.partrove.com/common/site/logo.png']
email = "partrove@gmail.com"

# footerBottomText = ""

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

siteStartYear = 2024

favicon = "https://gn-img-a1.partrove.com/common/site/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# showPrevNextPost = true

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"

# [services]
# [services.disqus]
# shortname = "partrove"